{{- if .Values.cloudflare.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cloudflare
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-cloudflare
  template:
    metadata:
      labels:
        app: external-dns-cloudflare
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.15.1
        env:
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: apiKey
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: email
        args:
        - --source=ingress
        - --source=service
        - --provider=cloudflare
        {{ if .Values.cloudflare.proxied }}
        - --cloudflare-proxied
        {{ end }}
        {{ if .Values.cloudflare.target }}
        - --default-targets={{ .Values.cloudflare.target }}
        {{ end }}
        - --domain-filter={{ .Values.cloudflare.domainFilter }}
        - --log-level={{ .Values.cloudflare.logLevel }}
        - --log-format=text
        - --interval={{ .Values.cloudflare.interval }}
        {{ if .Values.cloudflare.dryRun }}
        - --dry-run
        {{ end }}
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
{{- end }}
