# Pi-hole configuration
# password: admin
# piholeServer: http://pihole-web.pihole.svc.cluster.local
# targetNamespace: external-dns
# domainFilter: 'internal.zilinek.fun'
logLevel: info
dryRun: true
interval: 3m

# Cloudflare configuration
# Note: Create a secret manually named 'cloudflare-api-key' with keys 'apiKey' and 'email'

# kubectl create secret generic cloudflare-api-key \
#   --from-literal=apiKey=YOUR_API_KEY \
#   --from-literal=email=your-email@example.com \
#   -n external-dns

cloudflare:
  enabled: false
  # domainFilter: 'zilinek.fun'
  # target: '37.143.116.177'  # Override target IP for all DNS records
  logLevel: info
  dryRun: false
  interval: 5m
  proxied: true
